### ISSUE TITLE
Error thrown in iCloud Service

### ISSUE THREAD

**Issue by austince** [meetfranz/franz#1629]
**Describe the bug**

Cannot load iCloud Service, error thrown in Service dev tools:

```
/opt/Franz/resources….development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Services (created by Jss(Services))
    in Jss(Services) (created by AppLayoutContainer)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in div (created by AppLayout)
    in ErrorBoundary (created by Jss(ErrorBoundary))
    in Jss(ErrorBoundary) (created by AppLayout)
    in AppLayout (created by Jss(AppLayout))
    in Jss(AppLayout) (created by AppLayoutContainer)

/opt/Franz/resources/app.asar/node_modules/prop-types/checkPropTypes.js:20
Warning: Failed openExternalUrl type: The openExternalUrl `url` is marked as required in `<<anonymous>>`, but its value is `null`

internal/url.js:239 Uncaught NodeError: Invalid URL: null
    at onParseError (internal/url.js:237:17)
    at parse (internal/url.js:246:3)
    at new URL (internal/url.js:321:5)
    at AppStore._openExternalUrl (/opt/Franz/resources/app.asar/stores/AppStore.js:319:23)
    at executeAction$$1 (/opt/Franz/resources/app.asar/node_modules/mobx/lib/mobx.js:579:19)
    at AppStore.res (/opt/Franz/resources/app.asar/node_modules/mobx/lib/mobx.js:571:16)
    at action.listeners.forEach.listener (/opt/Franz/resources/app.asar/actions/lib/actions.js:29:68)
    at Array.forEach (<anonymous>)
    at Function.action.notify.params [as notify] (/opt/Franz/resources/app.asar/actions/lib/actions.js:29:48)
    at Object.action [as openExternalUrl] (/opt/Franz/resources/app.asar/actions/lib/actions.js:14:14)

```

**To Reproduce**
1. Add the iCloud Service
2. Open it and observe it cannot load
3. Open dev tools

**Expected behavior**

The iCloud Service should not throw errors.

**Desktop:**
 - OS: Ubuntu 18.04
 - Franz Version: 5.3.1

**Comment by austince** [comment]
not stale
