### ISSUE TITLE
Franz 5.4.1 not starting up

### ISSUE THREAD

**Issue by dima2306** [meetfranz/franz#1698]
**Describe the bug**
I'm using Franz on Fedora 31. When I launch Franz via icon I see processes, but no GUI.
When I launched it through the terminal, I see this log:
`SyntaxError: /home/[user-name-here]/.config/Franz/config/proxy.json: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at readFileSync (/tmp/.mount_Franz-yfjn2o/resources/app.asar/node_modules/jsonfile/index.js:63:17)
    at Settings._hydrate (/tmp/.mount_Franz-yfjn2o/resources/app.asar/electron/Settings.js:64:56)
    at new Settings (/tmp/.mount_Franz-yfjn2o/resources/app.asar/electron/Settings.js:41:12)
    at Object.<anonymous> (/tmp/.mount_Franz-yfjn2o/resources/app.asar/index.js:66:23)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Object.<anonymous> (/tmp/.mount_Franz-yfjn2o/resources/electron.asar/browser/init.js:181:12)
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
`

**To Reproduce**
1. Try starting the Franz

**Expected behavior**
Launch a program with GUI

**Additional context**
Previously I was using Franz 5.3.3 which was working fine. I've reset cache from Franz settings and after this it's not starting. Same is for 5.4.1 version...

**Comment by dima2306** [comment]
`/home/[user-name-here]/.config/Franz/config/proxy.json` renamed `proxy.json` and started Franz again, which caused new `proxy.json` to be created and hooray, GUI has started.

**Comment by fyto5** [comment]
Just renamed both files json in
c:\Users\<username>\AppData\Roaming\Franz\config\
and it's working. Thanks Dima!!! Your solutions rocks!!!!!!!!!!!!
And if it does it again I will create a batch file fo it :)

**Comment by dima2306** [comment]
@fyto5 I'm glad that my workaround worked for you.
Still hope we won't need to use it in future updates))
