### ISSUE TITLE
Could not load service recipe

### ISSUE THREAD

**Issue by An3skmbi** [meetfranz/franz#171]
Franz 5.0.0-beta.11: When adding any service I get a red error message "Could not load service recipe."
I am behind a proxy which might be causing the issue. Franz 4.0.4 works fine.

### Screenshots (if appropriate):
![capture](https://user-images.githubusercontent.com/2877453/32157148-5d9cc7f2-bd4a-11e7-833d-c98811b7bc90.PNG)

### Possible Solution
Allow user to edit proxy settings.

### Your Environment
* Franz Version used: 5.0.0-beta.11
* Operating System and version: Win 10

**Comment by adlk** [comment]
Thanks for reporting this. While Franz should be working with most of the proxy servers, we have seen some windows/proxy setups where this wasn't the case.

I need to do more research and hope that I will be able to fix this issue soon.

**Comment by An3skmbi** [comment]
Cool. Here is some more detail if it helps:

Proxy settings are applied via AD group policy, here is the settings in IE:

![capture](https://user-images.githubusercontent.com/2877453/32163330-a1e6a7a6-bd64-11e7-9720-2a6ce41e40ee.PNG)

As mentioned, Franz 4 worked without issue and I never did any manual proxy config.

**Comment by adlk** [comment]
Thanks for the additional info. 

We have decoupled services in Franz 5 from the app itself to avoid a lot of issues. However, it brings new ones – but nothing we can't fix :)

**Comment by kloknibor** [comment]
I'can report the same error. My laptop is also behind a proxy or VPN. If I can supply any info to help please let me know!

**Comment by cicciofuser** [comment]
same problem on xubuntu 16.04

**Comment by erolando** [comment]
same problem on mac os sierra 10.12.6

**Comment by maxnth** [comment]
Same problem on Manjaro 17.1-pre3

**Comment by pat-s** [comment]
Same problem on Arch KDE. Only Github service is loading

**Comment by GuillaumeLagrange** [comment]
Same problem with Arch, no proxy. Some services like Github or Trello load, but most do not.
5.0.0-beta.14

**Comment by ludcl** [comment]
Same problem with Manjaro Linux 17.1-pre3, no proxy nor VPN using version 5.0.0-beta.14

**Comment by falsified** [comment]
Ditto here.. Arch, no proxy/vpn, compiled 5.0.0-beta.14
version 4.x however does work

**Comment by linusheinz** [comment]
Same here. Arch, no proxy/vpn, compiled 5.0.0-beta.14

**Comment by tsusanka** [comment]
Same here. Manjaro Linux 17.0.6. No vpn, no proxy.

Can I help to debug this anyhow? This renders Franz unfortunately completely unusable

**Comment by blufor** [comment]
**Confirming the bug**

- version `5.0.0-beta.14`
- no proxy
- no VPN
- Arch linux

**Comment by falsified** [comment]
Very odd.. after running app image, the beta works fine now (unless you've made any changes since).

**Comment by pat-s** [comment]
@adlk the AppImage works for me as well! :+1:

**Comment by adlk** [comment]
@falsified the AppImage was created from the [beta 14 tag](https://github.com/meetfranz/franz/tree/v5.0.0-beta.14). So it is exactly the same source as it should be in the Arch repo. 

@all when you run into this issue, please open the dev tools and take a look in the console and network tab, maybe there is something useful in there.

**Comment by cicciofuser** [comment]
@adlk actualli I download again the deb package, installed again with gdebi and the app is working now. Quite weird

**Comment by tsusanka** [comment]
@adlk I'm getting this error in the console:
```
Error: /home/tomas/.config/Franz/recipes/temp/whatsapp/package.json: ENOENT: no such file or directory, open '/home/tomas/.config/Franz/recipes/temp/whatsapp/package.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Object.readFileSync (/usr/share/franz/resources/app.asar/node_modules/fs-extra/node_modules/jsonfile/index.js:67:22)
    at ServerApi.getRecipePackage (/usr/share/franz/resources/app.asar/api/server/ServerApi.js:326:40)
    at <anonymous>
```

The folder is present, but the package.json file is missing. I'll try to add an empty file now

**Comment by petermenzelme** [comment]
@adlk I can confirm what @tsusanka is reporting. 

I can reproduce the behavior on my Arch/Manjaro Deepin (17.0.6) System. The package is downloaded into `/home/peter/.config/Franz/recipes/temp/[recipe_name]/recipe.tar.gz` after beeing selected, but for some reason the automatic extraction of the package fails. 

When I extract/unpack that package manually in the `/home/peter/.config/Franz/recipes/[recipe_name]/` folder everything works just fine.

**Comment by adlk** [comment]
I just ran into issues with this myself. I have created a local build and I wasn't able to install recipes (tar.gz extraction). When I use the provided built from travis, everything is working again 

My first thought was that the package is not downloaded completely but the checksum checks out.

So atm, I have absolutely no clue what's happening but I'll keep investigating this issue.

**Comment by adlk** [comment]
We did quite some debugging and testing and I believe we have found a solution. 
If you are using custom builds, please try building from here: https://github.com/meetfranz/franz/tree/feature/harden-recipe-extraction

you can test the official travis build here: http://franz-travis.s3-website.eu-central-1.amazonaws.com/?prefix=484/

**Comment by hmhofman** [comment]
After testing with @adlk it seems the error has to do with synchronizing the recipe to the file system. 
Recipes are downloaded to the ~/.config/Franz/recipes/temp/ on Linux in .tar.gz format
Those recipes are then extracted and after that moved to the ~/.config/Franz/recipes/ folder. 
The extract command (https://github.com/meetfranz/franz/blob/v5.0.0-beta.14/src/api/server/ServerApi.js line 296) does not seem to sync to the file system. 

A work around would be to extract the files by hand (`cd` to the folder and `tar -xf recipe.tar.gz`) and then try to add the service again. Same goes if after a login not all your services get loaded. 

We might have a solution and it should be fixed in beta 15.

**Comment by tsusanka** [comment]
> you can test the official travis build here: http://franz-travis.s3-website.eu-central-1.amazonaws.com/?prefix=484/

I can confirm that this works. I've used the tar.gz archive and tried to add a service which I haven't used -> no error.

**Comment by tgalal** [comment]
@adlk it's not exactly the same as in Arch, at least installation wise. Arch's package pulls the latest  "tar" package; v4.1.1, while the one in the AppImage is 4.0.2. I found that the 4.1.1 version fails to extract the tar.gz file, and just swapping the tar package with the older one fixes it.

**Comment by hmhofman** [comment]
@adlk @tgalal I can confirm the package bump. 
When I cloned the repository this morning, it was version 4.0.2. 
Updated a lot of dependencies in just a few hours. 

Still, the feature branch `feature/harden-recipe-extraction` works for me.

**Comment by adlk** [comment]
@tgalal thanks for the info. It's difficult to say where the actual issue happens but as long as there is the `yarn.lock` present, yarn should install 4.0.2. But as you've commented on the Arch AUR repo, pinning the version is definitely a good idea until we know the source of the issue.

**Comment by An3skmbi** [comment]
Hi, OP here, running 5.0.0-beta.14 on Windows
I looked in dev tools console, I'm seeing the following error:

![capture](https://user-images.githubusercontent.com/2877453/33717425-988f2eb4-db62-11e7-9867-3b2d22c1d358.PNG)

Looks to be related to downloading of the recipes. There are folders in `C:\Users\xxx\AppData\Roaming\Franz\recipes\temp` like slack and gmail but they're empty.

**Comment by rvega** [comment]
+1 Manjaro with no proxy or vpn. Installed from AUR.

**Comment by adlk** [comment]
@An3skmbi you ran into the actual proxy issue. I'm going to test a small API change that there isn't a recipe package redirect but direct fetch. I'll let you know as soon as the test build is ready.

**Comment by gaoqi7** [comment]
After arch's latest update, Franz V4.0.4 works. no more error message "Could not load service recipe"

**Comment by itsagoodbrain** [comment]
@gaoqi7  That's the franz-bin AUR... which maintains the legacy version only. This is about the franz AUR which pulls the latest versions including beta.

**Comment by rafaellehmkuhl** [comment]
+1 AntergOS with no proxy.
Only Trello recipe works

**Comment by simonszu** [comment]
+1 on Arch via AUR, 5.0.0-beta.14. No proxy, no VPN. Only Trello works.

**Comment by jamesray1** [comment]
+1 on Manjaro Arch via AUR

Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64

No proxy or VPN. I tried Whatsapp, Messenger,

The app also froze while I had the settings window open. After closing and trying to open again, it didn't load.

I will try an earlier version e.g. 4.0.4 as mentioned above.

**Comment by skidnik** [comment]
> Next error. I have 82 of these, presumably the error occurs for each service request.

> ServerApi.js:380 TypeError: fetch is not a function
    at ServerApi.getRecipePackage (ServerApi.js:354)
    at ServicesApi.install (RecipesApi.js:11)
    at _promise.Promise (Request.js:44)
    at Promise (<anonymous>)
    at Request.execute (Request.js:43)
    at RecipesStore._install (RecipesStore.js:59)
    at executeAction (/usr/share/franz/resources/app.asar/node_modules/mobx/lib/mobx.js:915)
    at RecipesStore.res (/usr/share/franz/resources/app.asar/node_modules/mobx/lib/mobx.js:906)
    at ServicesStore._showAddServiceInterface (ServicesStore.js:138)
    at action.listeners.forEach.listener (actions.js:14)

Same for me. Installed from .rpm on Fedora 28. rpm built in a fedora 28 docker container from source cloned from [ github](https://github.com/meetfranz/franz) according to instructions from README.md.

**Comment by MikeDabrowski** [comment]
Happens on windows10 as well. Interesting that published version seems to work just fine.  Where was that 5.0.0 beta.18 build ?

**Comment by 3337777fw** [comment]
A pretty basic trouble shooting, but you might want to check if you are running an anti virus program on your Mac such as Kaspersky...
