### ISSUE TITLE
npm run dev FAILS on dev script

### ISSUE THREAD

**Issue by imawhale** [meetfranz/franz#1746]
**Describe the bug**
`npm run dev` fails on dev script with following error:

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! franz@5.4.1 dev: `cross-env NODE_ENV=development gulp dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the franz@5.4.1 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/home/.npm/_logs/2020-01-11T23_55_45_887Z-debug.log
```

**To Reproduce**
1. Follow donwload and install instructions
2. `npm run dev`
3. See error

**Expected behavior**
Run dev script without error.

**Desktop (please complete the following information):**
 - OS: Mac OS X Catalina 10.15.2
 - Terminal
 **- Node v12.14.0**

**Comment by imawhale** [comment]
**Log:**

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.13.6
3 info using node@v12.14.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle franz@5.4.1~predev: franz@5.4.1
6 info lifecycle franz@5.4.1~dev: franz@5.4.1
7 verbose lifecycle franz@5.4.1~dev: unsafe-perm in lifecycle true
8 verbose lifecycle franz@5.4.1~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/home/Library/Mobile Documents/com~apple~CloudDocs/codebase/create/platforms/ios/openSource/franz/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/home/icloud/mobile-apps/flutter/bin:/usr/local/go/bin:/Applications/Keybase.app/Contents/SharedSupport/bin
9 verbose lifecycle franz@5.4.1~dev: CWD: /Users/home/Library/Mobile Documents/com~apple~CloudDocs/codebase/create/platforms/ios/openSource/franz
10 silly lifecycle franz@5.4.1~dev: Args: [ '-c', 'cross-env NODE_ENV=development gulp dev' ]
11 silly lifecycle franz@5.4.1~dev: Returned: code: 1  signal: null
12 info lifecycle franz@5.4.1~dev: Failed to exec dev script
13 verbose stack Error: franz@5.4.1 dev: `cross-env NODE_ENV=development gulp dev`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid franz@5.4.1
15 verbose cwd /Users/home/Library/Mobile Documents/com~apple~CloudDocs/codebase/create/platforms/ios/openSource/franz
16 verbose Darwin 19.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.14.0
19 verbose npm  v6.13.6
20 error code ELIFECYCLE
21 error errno 1
22 error franz@5.4.1 dev: `cross-env NODE_ENV=development gulp dev`
22 error Exit status 1
23 error Failed at the franz@5.4.1 dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
