### ISSUE TITLE
Franz 5.7.0 crashing on macOS 11.4 Big Sur (M1 hardware)

### ISSUE THREAD

**Issue by robertklep** [meetfranz/franz#2077]
**Describe the bug**
When starting Franz 5.7.0, its main window appears in a flash, then the app crashes.

**To Reproduce**
Start the app.

**Expected behavior**
The app should start.

**Desktop (please complete the following information):**
 - OS: macOS 11.4 Big Sur (Mac mini M1, 2020)
 - Browser: Brave
 - Version: 1.29.79

**Additional context**

Services installed:
* Slack (twice, both disabled because of #2074)
* Whatsapp
* Tweetbot (twice)

I went back to 5.6.1, which works fine.

Starting the app from the command line yields the following log:
```
$ /Applications/Franz.app/Contents/MacOS/Franz
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@97] TypeError: Invalid Version: 11
    at new SemVer (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/semver/semver.js:323:11)
    at compare (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/semver/semver.js:614:39)
    at Function.gte (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/semver/semver.js:663:10)
    at Function.getVersion.isGreaterThanOrEqualTo (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/macos-version/index.js:61:16)
    at TrayIcon._getAsset (/Applications/Franz.app/Contents/Resources/app.asar/lib/Tray.js:104:102)
    at TrayIcon.show (/Applications/Franz.app/Contents/Resources/app.asar/lib/Tray.js:29:45)
    at /Applications/Franz.app/Contents/Resources/app.asar/electron/ipc-api/appIndicator.js:31:23
    at reactionRunner (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1931:9)
    at trackDerivedFunction$$1 (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1100:24)
    at Reaction$$1.track (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1626:22)
[mobx] Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Autorun@97] TypeError: Invalid Version: 11
    at new SemVer (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/semver/semver.js:323:11)
    at compare (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/semver/semver.js:614:39)
    at Function.gte (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/semver/semver.js:663:10)
    at Function.getVersion.isGreaterThanOrEqualTo (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/macos-version/index.js:61:16)
    at TrayIcon._getAsset (/Applications/Franz.app/Contents/Resources/app.asar/lib/Tray.js:104:102)
    at TrayIcon.show (/Applications/Franz.app/Contents/Resources/app.asar/lib/Tray.js:29:45)
    at /Applications/Franz.app/Contents/Resources/app.asar/electron/ipc-api/appIndicator.js:31:23
    at reactionRunner (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1931:9)
    at trackDerivedFunction$$1 (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1100:24)
    at Reaction$$1.track (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1626:22)
[1]    8339 segmentation fault  /Applications/Franz.app/Contents/MacOS/Franz
```

**Comment by ebuswf** [comment]
Same here

**Comment by macCesar** [comment]
Same here in a brand new Mac mini.

**Comment by sebastienbarre** [comment]
Same here. It takes restarting it a few times for it to finally stick. Macbook Pro M1 MAX

**Comment by WladyX** [comment]
Had 0 issues with Ferdi on Mac Pro 13 M1

**Comment by renegeorgi** [comment]
Same here. But only on my MacBook Pro M1 Max – On Mac Mini it works just fine.

**Comment by nowy57** [comment]
ooh very annoying , same to me , macbook pro 16 m1MAX

**Comment by nowy57** [comment]
I FOUND SOLUTION :) 
https://getferdi.com

**Comment by macCesar** [comment]
Perfect!! Thanks!!

**Comment by Yelizaroff** [comment]
> I FOUND SOLUTION :)
> https://getferdi.com

Thanks!!! Great!!!
