### ISSUE TITLE
Importing services from 4.0.4 failed for 5.0.0 beta 10 on OSX

### ISSUE THREAD

**Issue by huyz** [meetfranz/franz#22]
I installed 5.0.0 beta 10 and, while it listed all my old services from 4.0.4 and said that it was going to import them, my 5.0 app was simply empty.

### Expected Behavior

My listed services should have been imported from 4.0.4 to 5.0.0

### Current Behavior

Only the first screen shows up: listing of the services to be imported.
But then the list of my services is empty.

### Steps to Reproduce (for bugs)

1. Set up some services on 4.0.4
2. Install 5.0.0 beta 10
3. Create an account
4. Accept importing all the services from 4.0.4

### Context

Trying out 5.0.0 beta 10

### Your Environment

* Franz Version used: 5.0.0 beta 10
* Operating System and version: OS X 10.11.6

**Comment by adlk** [comment]
@huyz Can you please check, based on the console output (`cmd/ctrl+shift+alt+i`), if this is an issue in the client or API?

**Comment by huyz** [comment]
Here's the error I get from the console:

```
/Applications/Franz.app/Contents/Resources/app.asar/node_modules/fbjs/lib/warning.js:33 Warning: forceUpdate(...): Cannot update during an existing state transition (such as within `render` or another component's constructor). Render methods should be a pure function of props and state; constructor side-effects are an anti-pattern, but can be moved to `componentWillMount`.
printWarning @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/fbjs/lib/warning.js:33
warning @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/fbjs/lib/warning.js:57
getInternalInstanceReadyForUpdate @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:52
enqueueForceUpdate @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdateQueue.js:146
ReactComponent.forceUpdate @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react/lib/ReactBaseClasses.js:83
(anonymous) @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:749
Reaction.runReaction @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3054
runReactionsHelper @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3186
reactionScheduler @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3164
(anonymous) @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3193
batchedUpdates @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatching…:58
batchedUpdates @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:95
reactionScheduler @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3193
runReactions @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3169
endBatch @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:2718
Reaction.track @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3093
reactiveRender @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx-react/index.js:768
(anonymous) @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:793
measureLifeCyclePerf @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:73
_renderValidatedComponentWithoutOwnerOrContext @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:792
_renderValidatedComponent @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:819
_updateRenderedComponent @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:743
_performComponentUpdate @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:721
updateComponent @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:642
performUpdateIfNecessary @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactCompositeCompon…:558
performUpdateIfNecessary @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactReconciler.js:154
runBatchedUpdates @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:148
perform @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:141
perform @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:141
perform @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:87
flushBatchedUpdates @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:170
closeAll @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:207
perform @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/Transaction.js:154
batchedUpdates @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactDefaultBatching…:60
batchedUpdates @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/react-dom/lib/ReactUpdates.js:95
reactionScheduler @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3193
runReactions @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:3169
endBatch @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:2718
BaseAtom.reportChanged @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:68
ObservableValue.setNewValue @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:818
setPropertyValue @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1693
set @ /Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:1645
_importLegacyServices @ UserStore.js:203
ServicesStore.js:463 Uncaught (in promise) TypeError: Cannot read property 'hasTeamId' of undefined
    at ServicesStore._cleanUpTeamIdAndCustomUrl (/Applications/Franz.app/Contents/Resources/app.asar/stores/ServicesStore.js:509:15)
    at ServicesStore._createService (/Applications/Franz.app/Contents/Resources/app.asar/stores/ServicesStore.js:182:23)
    at executeAction (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:915:19)
    at ServicesStore.res (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:906:16)
    at action.listeners.forEach.listener (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:20:70)
    at Array.forEach (native)
    at Function.action.notify.params [as notify] (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:20:50)
    at Object.action [as createService] (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:15:16)
    at ServicesStore._createFromLegacyService (/Applications/Franz.app/Contents/Resources/app.asar/stores/ServicesStore.js:214:26)
    at executeAction (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:915:19)
    at ServicesStore.res (/Applications/Franz.app/Contents/Resources/app.asar/node_modules/mobx/lib/mobx.js:906:16)
    at action.listeners.forEach.listener (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:20:70)
    at Array.forEach (native)
    at Function.action.notify.params [as notify] (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:20:50)
    at Object.action [as createFromLegacyService] (/Applications/Franz.app/Contents/Resources/app.asar/actions/lib/actions.js:15:16)
    at UserStore._importLegacyServices (/Applications/Franz.app/Contents/Resources/app.asar/stores/UserStore.js:278:28)
```

Screenshot
![image](https://user-images.githubusercontent.com/128394/31767401-195e82b8-b4f5-11e7-824e-c336e80ffead.png)

The last error is repeated for a total of 12 times, one for each of the services I'm trying to import.
Btw, to reproduce this bug, I have to always create a new account.

Still need my `services.json` ?

**Comment by BinaryBen** [comment]
Same happened for me. Same console output as huyz.

**Comment by adlk** [comment]
@huyz that's fine, thanks a lot!

I'll look into it and fix this with the next version.

**Comment by adlk** [comment]
@huyz I've been a little to fast. Can you please share your service.json or send it to me directly? stefan@adlk.io

**Comment by nsudds** [comment]
I had the same problem on Windows 10 -- it asked me about importing but then didn't import anything.

**Comment by sf0524** [comment]
I have also been in the same situation as this...

macOS 10.12.6, Franz Ver: 4.0.4 > 5.0.0 beta 10

**Comment by nsudds** [comment]
I went ahead and added everything manually, didn't take too long and feels much better than 4.0.4 -- just not seeing any desktop notifications, maybe that's not built out yet in 5 beta. Other than that, overall liking 5 much better.

**Comment by SergioSGil** [comment]
+1
