### ISSUE TITLE
Beta 14 - Caching issue?

### ISSUE THREAD

**Issue by alecive** [meetfranz/franz#369]
I am using beta 14 on Ubuntu 14.04, and I have the following issues:

 1. every time I open franz, my office 365 session is logged out and I have to log back in again
 2. every time one of my slack channels is out of focus (so not everytime I re-start franz), it seems to be logging out and for whatever reason it takes forever to reload, making all my slack channels unusable.

**Comment by alecive** [comment]
This is the output of my console (please notice the possible memory leak):

```
rollup-core_required_libs.8e73dad….min.js:93 Warning: a promise was created in a handler but was not returned from it
    at M (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:17087)
    at O.r._warn (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:13380)
    at Object.I [as checkForgottenReturns] (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:16899)
    at O._settlePromiseFromHandler (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:50842)
From previous event:
    at O.P [as _captureStackTrace] (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:16419)
    at O._resolveFromExecutor (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:50178)
    at new O (https://a.slack-edge.com/bv1-1/rollup-core_required_libs.8e73dada0d381d3f8d4b.min.js:93:43920)
    at /opt/Franz/resources/app.asar/node_modules/electron-spellchecker/lib/spell-check-handler.js:73:99
    at SpellCheckHandler.switchLanguage (/opt/Franz/resources/app.asar/node_modules/electron-spellchecker/lib/spell-check-handler.js:465:7)
    at Spellchecker.enable (/opt/Franz/resources/app.asar/webview/spellchecker.js:22:25)
    at EventEmitter._electron.ipcRenderer.on (/opt/Franz/resources/app.asar/webview/plugin.js:39:20)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
v @ rollup-core_required_libs.8e73dad….min.js:93
rollup-core_required_libs.8e73dad….min.js:93 Uncaught Error: cannot enable cancellation after promises are in use
    at Function.r.config (rollup-core_required_libs.8e73dad….min.js:93)
    at e (rollup-core_required_ts.1dbcd33….min.js:1)
    at Object.e [as boot] (rollup-core_required_ts.1dbcd33….min.js:1)
    at messages:2279
rollup-core_required_libs.8e73dad….min.js:201 SoundManager 2: No Flash detected. Trying HTML5-only mode.
rollup-core_required_libs.8e73dad….min.js:201 SoundManager V2.97a.20150601 (HTML5-only mode)
rollup-core_required_libs.8e73dad….min.js:201 SoundManager 2 HTML5 support: mp3 = true, mp4 = true, ogg = true, opus = true, wav = true
rollup-core_required_libs.8e73dad….min.js:201 SoundManager 2: Ready. ✓
webview.js:5 getTeamIcon 0
webview.js:10 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at getTeamIcon (webview.js:10)
    at setTimeout (webview.js:38)
internal/process/warning.js:21 (node:3071) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 electron-remote-event-webcontents-5-context-menu-5 listeners added. Use emitter.setMaxListeners() to increase limit
process.on @ internal/process/warning.js:21
```

**Comment by alecive** [comment]
Update: actually, slack channels are NEVER loaded. This does not happen in beta 13, though.

**Comment by alecive** [comment]
Similar to #369 (since my slack channels did not work, I had to downgrade to beta 13 before receiving the notivication about #369 :sunglasses: ). Closing.
