### ISSUE TITLE
Custom Recipe Development, JS Error: Unexpected Token Import

### ISSUE THREAD

**Issue by tspaulding0222** [meetfranz/franz#389]
Attempting to create a custom discord recipe. After dragging files into the dev folder inside of library. Once I go to run the service the js console outputs:
```
eafb5fe485657e3e10aa.js:17 SyntaxError: Unexpected token import
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at EventEmitter._electron.ipcRenderer.on (/Applications/Franz.app/Contents/Resources/app.asar/webview/plugin.js:30:5)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by adlk** [comment]
you need to replace `import foo from 'foo';` with `const foo = require('foo');`

This needs to be updated in the docs as we are transpiling the recipes before deployment.
