### ISSUE TITLE
Sleep issues causing Franz to lose service webviews

### ISSUE THREAD

**Issue by haraldox** [meetfranz/franz#594]
this is a super-issue dealing aggregating all things sleep from previous issues, please use only this issue to comment:

- grey webview not loading service after sleep: #168, #589, #591, #593

**Comment by andypillip** [comment]
I'm still seeing blank screens after resume on Gnome 3.26.

**Comment by JayM1212** [comment]
same issue here

**Comment by brendanjones** [comment]
No idea if this is petinent to the issue at hand, but in the moment after wake-up before my computer reconnects internet, it still displays the "You are not connected to the internet" message, even though the service doesn't display anyway once the internet is connected:

![screen shot 2018-01-19 at 1 19 54 pm](https://user-images.githubusercontent.com/16049594/35150759-df2b02d2-fd1b-11e7-9353-62b76afb06a1.png)

**Comment by Exide** [comment]
I have the same or similar issue as #168 and #589. I use the HipChat and Hangouts services and both are blank when waking my system. The HipChat service is especially painful as it requires authenticating again.

MacOS 10.12.5
Franz 5.0.0-beta.15.607

**Comment by deepak365** [comment]
I am facing the same issue with WhatsApp, telegram, and slack.

**Comment by carlba** [comment]
I am also having the same issue.

Franz 5.0.0-beta.15
MacOS 10.13.1 (17B1003)

**Comment by dapierce** [comment]
Having the same issue as well, using Slack, Messenger and Tweetdeck. Grey window with the 3 service icons on the left panel. Quitting Franz and reopening fixes the problem for me.

Franz 5.0.0-beta.15
Windows 10 1709 (build 16299.192)

**Comment by jjmurre** [comment]
Same issue here on Ubuntu 16:04
Version: 5.0.0-beta.15
Release: 1.7.9 / linux / x64

**Comment by nickschot** [comment]
Same on MacOS 10.13.3 with Slack/Facebook/Gitter
Version: 5.0.0-beta.15

**Comment by fagiani** [comment]
@adlk looks like this is happening a lot lately and this wasn't an issue i've noticed before the last couple releases. Any chance a recent change would have caused that and could be eventually reverted? Thanks for the amazing work on Franz!

**Comment by dkpalmer** [comment]
Same issue on Mac 10.13.2. Facebook Messenger and Google Hangouts.
Version 5.0.0-beta.15

Requires killing the app and restarting to resolve.

**Comment by leitmedium** [comment]
Having the same issue.

Workaround: Reload (instead of restart). E.g. on a Mac: press <COMMAND>-<R> - keep in mind, that this is still a browser.

**Comment by ignaty** [comment]
Same issue with Facebook Messenger and Slack. WhatsApp on other hand is working just fine.

Franz - 5.0.0-beta.15.607
Mac OS - 10.13.3 (17D47)

**Comment by brendanjones** [comment]
Besides Whatsapp, are there any other services this doesn't affect? I haven't come across any yet.

@dkpalmer you shouldn't need to kill Franz to fix this, just refresh the service or all of Franz. command+R or command+shift+R.

**Comment by haraldox** [comment]
we tried reproducing the issue, but it is simply not possible for us (happens too seldom or not at all and we really tried often) and if it occurs there are no error messages in either console or debug output... the only message i came across was

`
ServicesStore.js:404 Uncaught TypeError: Cannot read property 'loadURL' of null at ServicesStore._reload (/Users/H/franz/build/stores/ServicesStore.js:460:20) at executeAction (/Users/H/franz/node_modules/mobx/lib/mobx.js:867:19) at ServicesStore.res (/Users/H/franz/node_modules/mobx/lib/mobx.js:858:16) at enabled.forEach.s (/Users/H/franz/build/stores/ServicesStore.js:474:36) at Array.forEach (native) at ServicesStore._reloadAll (/Users/H/franz/build/stores/ServicesStore.js:474:18) at executeAction (/Users/H/franz/node_modules/mobx/lib/mobx.js:867:19) at ServicesStore.res (/Users/H/franz/node_modules/mobx/lib/mobx.js:858:16) at action.listeners.forEach.listener (/Users/H/franz/build/actions/lib/actions.js:20:70) at Array.forEach (native)
`

BTW this was supposed to be fixed in the code [here](https://github.com/meetfranz/franz/blob/a4b665ef5f218313e524f0582d08cde6aa5d7049/src/stores/AppStore.js#L398)

**Comment by philippeller** [comment]
Happens consistently on windows 10 after the computer goes to `hibernate`, does not happen after just `sleep`.
This is the log output, while the services (except for whatsapp) are still blank:
```
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s=1252&dl…9392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=747546009:1 GET https://www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s…699392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=747546009 net::ERR_NETWORK_IO_SUSPENDED
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s=1253&dl…9392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=941540900:1 GET https://www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s…699392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=941540900 net::ERR_NETWORK_IO_SUSPENDED
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s=1254&dl…9392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=424012164:1 GET https://www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s…699392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=424012164 net::ERR_NETWORK_IO_SUSPENDED
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
stores\AppStore.js:403 reactivateServices: reload all services
stores\AppStore.js:146 [Violation] 'setInterval' handler took 1252ms
lib\analytics.js:37 GA track page Settings update
www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s=1255&dl…9392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=216818292:1 GET https://www.google-analytics.com/collect?v=1&_v=j66&a=1062177416&t=event&_s…699392.1514890061&tid=UA-74126766-6&_gid=1065922391.1518581907&z=216818292 net::ERR_NETWORK_CHANGED
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
stores\ServicesStore.js:539 set badge 0 0
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
stores\ServicesStore.js:539 set badge 0 0
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
stores\ServicesStore.js:539 set badge 0 0
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
stores\ServicesStore.js:539 set badge 0 0
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
stores\ServicesStore.js:539 set badge 0 0
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
api\server\LocalApi.js:24 LocalApi::getAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
api\server\LocalApi.js:15 LocalApi::updateAppSettings resolves Object {appStarts: 19, autoLaunchOnStart: true, autoLaunchInBackground: false, runInBackground: true, enableSystemTray: true…}
lib\analytics.js:37 GA track page Settings update
```

**Comment by haraldox** [comment]
@philippeller nothing out of the ordinary 😕

**Comment by philippeller** [comment]
@haraldox yeah, but it also does not show the `reactivating services` output from the function you quoted above.....so it seems it never really gets there (?)
Let me know if there are any tests i can do...

**Comment by philippeller** [comment]
ah no it does! my bad

**Comment by haraldox** [comment]
only in debug level of the console

**Comment by SylvainCecchetto** [comment]
In addition to Riot, I have the same issue with Trello.

**Comment by tiagoboldt** [comment]
@haraldox this happens to me consistently after sleep. Laters OSX, Franz Version 5.0.0-beta.15. Is there anything I can provide to help debug this?

**Comment by leitmedium** [comment]
Two guesses:

1. I am running Franz on a rather old iMac.
2. In a similar ticket somebody mentioned it might be related to hardware acceleration (which might be related to older hardware preventing you from seeing the issue).

**Comment by tiagoboldt** [comment]
By observation, I've noticed that after waking up, franz operates correctly, it even updated the services status, the focused service loads the recent messages and then it gets greyed out.

**Comment by kMikaZu** [comment]
Same issue here. And not only after sleep. It happens after some time of inactivity.

**Comment by brendanjones** [comment]
This is now happening after periods of inactivity for myself as well as after sleep. 

On wakeup I notice the same process as @tiagoboldt , above. For me when that happens I refresh the service and the service displays, but with a 100px-ish border on the right and bottom of the service. This persists even after service refresh _and_ Franz-wide refresh. See screenshot:
![screen shot 2018-03-19 at 4 08 01 pm](https://user-images.githubusercontent.com/16049594/37603972-30572314-2b90-11e8-882c-fd24cc1c8bc5.png)

**Comment by pdrosos** [comment]
I have the same issue on Linux Mint 19.

After I close my laptop and it goes to Suspend mode, after opening it again when it wakes up, the Franz services windows (all of them - FB Messenger, Gmail and Hangouts) are empty and I need to reload them, so they show up again.

**Comment by FlipEverything** [comment]
Same on Ubuntu 18.04.1. (GNOME 3.28.2) with Gmail/Messenger/Slack
Version: 5.0.0-beta.18
Release: 1.8.4 / linux / x64
After sleep I have to reload every tab.

**Comment by aiguofer** [comment]
Happens on my Fedora 29, i3, using Slack and Hangouts Chat.

Until just now, I thought it was every time, but if I only suspend for a short period (like a few seconds) it didn't seem to happen.

**Comment by rionita** [comment]
Still seeing this issue on Windows 10 Pro:
Franz version 5.0.0 beta19
release 2.0.13 / win32 / x64

Clicking View > Reload Franz doesn't work when in that state, I can use Ctrl+Shift+R, still very annoying.

**Comment by FlipEverything** [comment]
Still seeing this issue on Ubuntu 18.04.1. (GNOME 3.28.2) with Gmail/Messenger/Slack
Version: 5.0.0-beta.22
Release: 2.0.13 / linux / x64
After sleep I have to reload every tab.

**Comment by Gr3yh0und** [comment]
Same here on Windows 10. Happens nearly every time the system goes to standby... Service doesn't matter much (Telegram, Whatsapp, Hangouts, FB Messenger...)
