### ISSUE TITLE
Services are gone from Franz and I can't readd any of them

### ISSUE THREAD

**Issue by markisa2804** [meetfranz/franz#827]
I had to do Windows system restore and Franz stopped working after that. It won't open.. I uninstalled franz, reinstall it, but now no services available and I am unable to add any service. 

Please see the screen recording here

https://drive.google.com/open?id=1XRV-mwJ0bS4BCPyjN3wjXlMpjBwRc9PK

### Screenshots (if appropriate):
https://drive.google.com/open?id=1XRV-mwJ0bS4BCPyjN3wjXlMpjBwRc9PK

### Steps to Reproduce (for bugs)

Refer to video here for steps
https://drive.google.com/open?id=1XRV-mwJ0bS4BCPyjN3wjXlMpjBwRc9PK

### Context
 Unable to use Franz at all

### Your Environment

* Franz Version used: 5.0 Beta 17
* Operating System and version: Windows 10

**Comment by adlk** [comment]
Please go to 
- Menu -> View -> Toggle Developer Tools
- Go to "console"

are there any errors?

**Comment by markisa2804** [comment]
Ah, I did not notice the developer tools! 
Yes, there are errors.. They are the same no matter what service I tried to add. 

warn whatsapp EPERM: operation not permitted, chmod 'C:\'
module.js:485 Uncaught (in promise) Error: Cannot find module 'trello'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (C:\Users\yosep\AppData\Local\Programs\franz\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at recipes.paths.map.id (C:\Users\yosep\AppData\Local\Programs\franz\resources\app.asar\api\server\ServerApi.js:304:22)
    at Array.map (native)
    at ServerApi.getInstalledRecipes (C:\Users\yosep\AppData\Local\Programs\franz\resources\app.asar\api\server\ServerApi.js:303:26)
    at ServicesApi.all (C:\Users\yosep\AppData\Local\Programs\franz\resources\app.asar\api\RecipesApi.js:12:24)
    at _promise.Promise (C:\Users\yosep\AppData\Local\Programs\franz\resources\app.asar\stores\lib\CachedRequest.js:49:30)
Module._resolveFilename @ module.js:485
Module._resolveFilename @ C:\Users\yosep\AppData\Local\Programs\franz\resources\electron.asar\common\reset-search-paths.js:35
Module._load @ module.js:437
Module.require @ module.js:513
require @ internal/module.js:11
recipes.paths.map.id @ api\server\ServerApi.js:276
getInstalledRecipes @ api\server\ServerApi.js:274
all @ api\RecipesApi.js:7
_promise.Promise @ stores\lib\CachedRequest.js:42
execute @ stores\lib\CachedRequest.js:41
invalidate @ stores\lib\CachedRequest.js:77
_install @ stores\RecipesStore.js:60
