### ISSUE TITLE
Linux build failed in `/node_module/macos-notification-state`

### ISSUE THREAD

**Issue by bartoszek** [meetfranz/franz#878]
I have a working franz, previously build on my os. But lately when trying to rebuild the package yarn throw an error about `macow-notification-state`...
My build script:
```
  3 pkgname=franz
  4 pkgver=5.0.0_beta.18
...
 13 source=("https://github.com/meetfranz/$pkgname/archive/v${pkgver//_/-}.tar.gz"
...
 24 build() {
 25   cd "$pkgname-${pkgver//_/-}"
 26   yarn install --production --non-interactive
 27   yarn add electron-builder gulpjs/gulp#4.0
 28   node_modules/.bin/gulp build
 29   node_modules/.bin/electron-builder --linux dir
 30 }
```

Error from yarn:
```
==> Starting build()...
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
 info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
info 7zip-bin-win@2.1.0: The platform "linux" is incompatible with this module.
info "7zip-bin-win@2.1.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.1.2: The platform "linux" is incompatible with this module.
info "fsevents@1.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-airbnb@14.1.0" has incorrect peer dependency "eslint@^3.15.0".
warning " > eslint-plugin-jsx-a11y@3.0.2" has incorrect peer dependency "eslint@^2.10.2 || 3.x".
warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
[4/4] Building fresh packages...
error An unexpected error occurred: "/build/franz/src/franz-5.0.0-beta.18/node_modules/macos-notification-state: Command failed.
Exit code: 1
Command: sh
Arguments: -c node-gyp rebuild
Directory: /build/franz/src/franz-5.0.0-beta.18/node_modules/macos-notification-state
Output:
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)".
```
[yarn-error.log](https://github.com/meetfranz/franz/files/1887260/yarn-error.log)

OS: ArchLinux #{nodejs=9.11.1, yarn=1.5.1, npm=5.8.1, node-gyp=3.6.2-1}
node-gyp located in `/usr/lib/node_module/node-gyp/` is this a problem ?
_My npm-foo is poor if any :/_

**Comment by timoc** [comment]
I had the same issue.
Its to do with the Frans build system not differentiating between linux, mac and windows and including mac and windows specific dependencies ("@meetfranz/electron-notification-state")
e.g. 
src/stores/AppStore.js:import { getDoNotDisturb } from '@meetfranz/electron-notification-state';

**Comment by bahawludba** [comment]
Did you ever find a fix for this?
